// packages/fe24-client-vue/src/components/common/virtual-list.vue
<script setup lang="ts">
import { computed, inject, reactive, ref, toRefs, type Ref } from 'vue'
import VirtualListItem from './virtual-list-item.vue'
import type { IRevenueItem } from '@/types/dashboard'

const props = defineProps<{
  // 可视区高度
  height: number
  // 列表项高度
  itemHeight: number
  // 获取列表项数组的函数
  fetchLargeList: () => Promise<IRevenueItem[]>
}>()

// 组件暴露接口
defineExpose<{
  updateLargeList: () => Promise<void>
}>({
  updateLargeList: async () => {
    largeList.value = await props.fetchLargeList()
    virtualListLength.value = largeList.value.length
  },
})

const virtualListLength = inject<Ref<number>>('virtual-list-length', ref(0) /** defaultVal */)

// 大列表
const largeList = ref(await props.fetchLargeList())
virtualListLength.value = largeList.value.length

// 可视区高度, 子项高度
const { height, itemHeight } = toRefs(props)

// 可视区子项数量
const visibleCnt = computed(() => {
  return Math.ceil(height.value / itemHeight.value)
})

// 可视区信息
const visibleInfo = reactive({
  startIdx: 0, // 起始索引
  endIdx: visibleCnt.value, // 结束索引
})

// 可视区数据
const visiblePartialList = computed(() => {
  return largeList.value.slice(
    visibleInfo.startIdx,
    Math.min(visibleInfo.endIdx, largeList.value.length),
  )
})

// 可视区起始偏移量
const startOffset = ref(0)

// 虚拟列表高度
const transformVal = computed(() => `translateY(${startOffset.value}px)`)
const largestListHeight = computed(() => largeList.value.length * itemHeight.value)

const handleScroll = (ev: Event) => {
  const scrollTop = (ev.target as HTMLDivElement).scrollTop
  visibleInfo.startIdx = Math.floor(scrollTop / itemHeight.value)
  visibleInfo.endIdx = visibleInfo.startIdx + visibleCnt.value
  // startOffset.value = scrollTop
  startOffset.value = visibleInfo.startIdx * itemHeight.value
}
</script>

<template>
  <!-- 可视区 container -->
  <div
    class="virtual-list relative overflow-auto bg-slate-50"
    @scroll="handleScroll"
    :style="{ height: height + 'px' }"
  >
    <!-- 虚拟区, 用于触发 overflow-auto -->
    <div :style="{ height: largestListHeight + 'px', width: 0 }"></div>

    <!-- 内容区 -->
    <ul
      class="absolute top-0 left-0 w-full bg-white"
      :style="{
        transform: transformVal,
      }"
    >
      <!-- ! truncate
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap; -->
      <li
        v-for="(item, idx) of visiblePartialList"
        :key="item.id"
        class="box-border rounded-lg"
        :style="{
          height: itemHeight + 'px',
          lineHeight: itemHeight + 'px',
        }"
      >
        <VirtualListItem :item="item" :idx="idx" />
      </li>
    </ul>
  </div>
</template>

<style scoped lang="scss">
.virtual-list::-webkit-scrollbar {
  display: none;
}
</style>

// packages/fe24-client/src/components/common/virtual-list.tsx
import React, { useState, useEffect, useMemo, useImperativeHandle, forwardRef } from 'react'
import VirtualListItem from './virtual-list-item'
import type { IRevenueItem } from '@/types/dashboard'

interface VirtualListProps {
  height: number
  itemHeight: number
  fetchLargeList: () => Promise<IRevenueItem[]>
}

export interface VirtualListRef {
  updateLargeList: () => Promise<void>
}

const VirtualList = forwardRef<VirtualListRef, VirtualListProps>(
  ({ height, itemHeight, fetchLargeList }, ref) => {
    const [largeList, setLargeList] = useState<IRevenueItem[]>([])
    const [scrollTop, setScrollTop] = useState(0)

    const loadData = async () => {
      const data = await fetchLargeList()
      setLargeList(data)
    }

    useEffect(() => {
      loadData()
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    useImperativeHandle(ref, () => ({
      updateLargeList: loadData,
    }))

    const visibleCnt = useMemo(() => Math.ceil(height / itemHeight), [height, itemHeight])

    const startIdx = Math.floor(scrollTop / itemHeight)
    const endIdx = startIdx + visibleCnt

    const visiblePartialList = useMemo(() => {
      return largeList.slice(startIdx, Math.min(endIdx, largeList.length))
    }, [largeList, startIdx, endIdx])

    const startOffset = startIdx * itemHeight
    const largestListHeight = largeList.length * itemHeight

    const handleScroll = (ev: React.UIEvent<HTMLDivElement>) => {
      setScrollTop(ev.currentTarget.scrollTop)
    }

    return (
      <div
        className="relative overflow-auto bg-slate-50"
        onScroll={handleScroll}
        style={{ height: `${height}px` }}
      >
        <div style={{ height: `${largestListHeight}px`, width: 0 }}></div>

        <ul
          className="absolute top-0 left-0 m-0 w-full list-none bg-white p-0"
          style={{
            transform: `translateY(${startOffset}px)`,
          }}
        >
          {visiblePartialList.map((item, index) => {
            // absolute index in largeList
            const realIdx = startIdx + index
            return (
              <li
                key={item.id}
                className="box-border rounded-lg"
                style={{
                  height: `${itemHeight}px`,
                  lineHeight: `${itemHeight}px`,
                }}
              >
                <VirtualListItem item={item} idx={realIdx} />
              </li>
            )
          })}
        </ul>
      </div>
    )
  },
)

VirtualList.displayName = 'VirtualList'

export default VirtualList
